### ISSUE TITLE
Congrats!

### ISSUE THREAD

**Issue by profnandaa** [kemboijs/kemboijs#8]
Hey Ez, just wanted to open and close this issue -- just to say, proud of you for this project! That's a great endeavor, congrats! 🎉

**Comment by profnandaa** [comment]
@ezrqnkemboi

**Comment by ezkemboi** [comment]
Thank you @profnandaa. 
You have been a great motivator on my side in terms of open source projects and Software development at large. 
That is why I always try to contribute by updating existing ones and creating other open-source projects.
